version: '3.8'

services:
  car_accumulator:
    build:
      context: ./car
      dockerfile: Dockerfile
    container_name: car_accumulator
    restart: always
    volumes:
      - ./car/CarDataAccumulator.py:/app/CarDataAccumulator.py
      - ../.env:/app/.env                # Mount .env from one level up
      - ../logging.conf:/app/logging.conf # Mount logging.conf from one level up
    environment:
      - DOTENV_PATH=/app/.env
    networks:
      - apars-greece-network

  satellite_accumulator:
    build:
      context: ./satellite
      dockerfile: Dockerfile
    container_name: satellite_accumulator
    restart: always
    volumes:
      - ./satellite/SatelliteDataAccumulator.py:/app/SatelliteDataAccumulator.py
      - ../.env:/app/.env
      - ../logging.conf:/app/logging.conf
    environment:
      - DOTENV_PATH=/app/.env
    networks:
      - apars-greece-network

  station_accumulator:
    build:
      context: ./station
      dockerfile: Dockerfile
    container_name: station_accumulator
    restart: always
    volumes:
      - ./station/StationDataAccumulator.py:/app/StationDataAccumulator.py
      - ./station/station_aqi_data.json:/app/station_aqi_data.json
      - ../.env:/app/.env
      - ../logging.conf:/app/logging.conf
    environment:
      - DOTENV_PATH=/app/.env
    networks:
      - apars-greece-network

networks:
  apars-greece-network:
    external: true
