name: demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.7.2
  flutter_map: ^6.0.0
  location: ^5.0.3
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.1.2
  flutter_svg: ^2.0.9
    
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


