services:
  apars-greece-context-broker:
    image: telefonicaiot/fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - apars-greece-context-broker-db
    command: -dbURI mongodb://apars-greece-context-broker-db
    networks:
      - apars-greece-network

  apars-greece-context-broker-db:
    image: mongo:6.0
    command: --nojournal
    volumes:
      - mongo-db:/data
    networks:
      - apars-greece-network
  
volumes:
  mongo-db:

networks:
  apars-greece-network:
    name: apars-greece-network
    driver: bridge