services:
  orion:
    image: telefonicaiot/fiware-orion
    platform: linux/amd64
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbURI mongodb://mongo

  mongo:
    image: mongo:6.0
    platform: linux/amd64
    command: --nojournal


  # webhook:
  #   build: .
  #   command: python orion/webhooks.py
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - orion
